# automatic merge conflict solving
#
# if any of the listed combinations of service names [and port] (e.g. `http` and
# `www`) are found as service names for the same port, the key is used as the
# conflict solving service name.
auto-merge:
# OS Rules
  - os:
      - windows
      - linux
    key:
      - unknown
#
  - os:
      - bsd
      - linux
    key:
      - unknown
#
  - os:
      - macos
      - linux
    key:
      - unknown
#
  - os:
      - macos
      - windows
    key:
      - unknown
#
  - os:
      - bsd
      - windows
    key:
      - unknown
# --------------------------------
# Service Rules
  - service-names:
      - http
      - www
    key: 
      - http
#
  - service-names:
      - https
      - www
    key:
      - https
#
  - service-names:
      - www
      - http
      - https
    port: 443
    key:
      - https
#
  - service-names:
      - http
      - https
    ports:
      - 443
      - 8443
    key:
      - https
#  
  - service-names:
      - http
      - https
    port: 80
    key:
      - http
#
  - service-names:
      - cifs
      - netbios-ssn
    port: 445
    key:
      - cifs
#  
  - service-names:
      - smtp
      - smtps
    port: 465
    key:
      - smtps
#
  - service-names:
      - smtp
      - smtps
    port: 587
    key:
      - smtps
#
  - service-names:
      - smtp
      - smtps
    port: 25
    key:
      - smtp
#
  - service-names:
      - dns
      - domain
    key:
      - dns
#  
  - service-names:
      - imap
      - imaps
    port: 993
    key:
      - imaps
#
  - service-names:
      - www
      - https
      - dc
    key:
      - https
#
  - service-names:
      - http_proxy
      - https
    key:
      - http_proxy
#
  - service-names:
      - http_proxy
      - http-proxy
      - http
    key:
      - http_proxy
#
  - service-names:
      - http_proxy
      - http
      - https
    key:
      - http_proxy
#
  - service-names:
      - epmap
      - msrpc
    port: 135
    key:
      - msrpc
#
  - service-names:
      - cifs
      - microsoft-ds
    port: 445
    key:
      - microsoft-ds
#
  - service-names:
      - cifs
      - microsoft-ds
      - smb
    port: 445
    key:
      - smb
#
  - service-names:
      - cifs
      - smb
    port: 445
    key:
      - smb
#
  - service-names:
      - ms-wbt-server
      - msrdp
    port: 3389
    key:
      - msrdp
#
  - service-names:
      - blackice-icecap
      - sunproxyadmin
    port: 8081
    key:
      - sunproxyadmin
#
  - service-names:
      - ms-sql-s
      - mssql
    key:
      - mssql
#
  - service-names:
      - netbios-ssn
      - smb
    port: 139
    key:
      - smb
#
  - service-names:
      - http
      - wsman
    port: 5985
    key:
      - http
#
  - service-names:
      - https
      - https-alt
    port: 8443
    key:
      - https
#
  - service-names:
      - https
      - wso2esb-console
    port: 9444
    key:
      - https
#
  - service-names:
      - http
      - https
    port: 31267
    key:
      - https
#
  - service-names:
      - accuracer
      - https
    port: 12007
    key:
      - https
#
  - service-names:
      - http
      - https
    port: 18084
    key:
      - https
#
  - service-names:
      - http
      - http-proxy
    port: 5800
    key:
      - http
#
  - service-names:
      - msrpc
      - dce-rpc
    key:
      - rpc
#
  - service-names:
      - jetdirect
      - pdl-datastream
    port: 9100
    key:
      - jetdirect
#
  - service-names:
      - https
      - http-proxy
    port: 8080
    key:
      - http/https/proxy
#
  - service-names:
      - abyss
      - http
    port: 9999
    key:
      - http
#
  - service-names:
      - http
      - https
    key:
      - http/https
#
  - service-names:
      - rpcbind
      - sunrpc
    key:
      - rpcbind/sunrpc
#
  - service-names:
      - remoteanything
      - terabase
    port: 4000
    key:
      - terabase
#
  - service-names:
      - cap
      - win-rpc
    port: 1026
    key:
      - win-rpc
#
  - service-names:
      - ipsec-nat-t
      - nat-t-ike
    port: 4500
    key:
      - ipsec-nat-t
#
  - service-names:
      - commplex-main
      - upnp
    port: 5000
    key:
      - upnp
#
  - service-names:
      - mdns
      - zeroconf
    port: 5353
    key:
      - mdns
#
  - service-names:
      - ssdp
      - upnp
    port: 1900
    key:
      - ssdp
#
  - service-names:
      - http-rpc-epmap
      - ncacn_http
    port: 593
    key:
      - ncacn_http
#
  - service-names:
      - ms-sql-s
      - mssql
    port: 49320
    key:
      - mssql
#
  - service-names:
      - apcpbeserver
      - powerchute
    port: 2160
    key:
      - powerchute
#
  - service-names:
      - apc-2161
      - apc-agent
    port: 2161
    key:
      - apc-agent
#
  - service-names:
      - apc-2260
      - apcpbeserver
    port: 2260
    key:
      - apcpbeserver
#
  - service-names:
      - dce-rpc
      - smap
    port: 3731
    key:
      - dce-rpc
#
  - service-names:
      - https
      - powerchuteplus
    port: 6547
    key:
      - https
#
  - service-names:
      - http
      - https
      - krb524
    port: 4444
    key:
      - https
#
  - service-names:
      - http
      - http_proxy
      - squid-http
    port: 3128
    key:
      - squid-http
#
  - service-names:
      - http
      - http_proxy
      - https
      - opsmessaging
    port: 8090
    key:
      - https
#
  - service-names:
      - http
      - ibm-db2
    port: 50000
    key:
      - ibm-db2
#
  - service-names:
      - bootps
      - dhcps
    port: 67
    key:
      - dhcps
#
  - service-names:
      - bootpc
      - dhcpc
    port: 68
    key:
      - dhcpc
#
  - service-names:
      - citrix
      - citrix-ica
    key:
      - citrix
#
  - service-names:
      - oracle-tns
      - oracle_tnslsnr
    key:
      - oracle-tns
#
  - service-names:
      - remoting
      - remoting_tcp
    key:
      - remoting_tcp
#
  - service-names:
      - kerberos
      - kerberos-sec
    key:
      - kerberos
#
  - service-names:
      - kpasswd
      - kpasswd5
    key:
      - kpasswd
#
  - service-names:
      - http
      - vnc-http
    key:
      - http/vnc-http
#
  - service-names:
      - http-proxy
      - vnc-http
    key:
      - http/vnc-http
#
  - service-names:
      - ndmp
      - netapp_ndmp
    key:
      - ndmp
#
  - service-names:
      - citrix-ima
      - citrixima
    key:
      - citrix-ima
#
  - service-names:
      - homepage
      - http
    key:
      - http
#
  - service-names:
      - homepage
      - http
      - https
    key:
      - https
#
  - service-names:
      - net-assistant
      - netassistant
    key:
      - netassistant
#
  - service-names:
      - uc4
      - uc4_executor
    key:
      - uc4
#
  - service-names:
      - activemq
      - apachemq
    key:
      - activemq
#
  - service-names:
      - http
      - nagios-nsca
    key:
      - nagios-nsca
#
  - service-names:
      - http
      - ipp
    port: 631
    key:
      - ipp
#
  - service-names:
      - rpc
      - rpcbind
    port: 111
    key:
      - rpc
#
  - service-names:
      - rpc-portmapper
      - rpcbind
    port: 111
    key:
      - rpc
#
  - service-names:
      - oracle-mts
      - http
    port: 2030
    key:
      - oracle-mts
#
  - service-names:
      - dameware
      - damewaremr
    port: 6129
    key:
      - dameware
#
  - service-names:
      - rpc-status
      - status
    key:
      - rpc
#
  - service-names:
      - nlockmgr
      - rpc-nlockmgr
    key:
      - rpc
#
  - service-names:
      - vmware-auth
      - vmware_auth
    key:
      - vmware-auth
#
  - service-names:
      - lpd
      - printer
    port: 515
    key:
      - lpd
#
  - service-names:
      - ms-sql-s
      - sybase
    key:
      - sybase/ms-sql-s
#
  - service-names:
      - mountd
      - rpc-mountd
    key:
      - mountd
#
  - service-names:
      - java-rmi
      - rmi_remote_object
    key:
      - java-rmi
#
  - service-names:
      - java-rmi
      - rmi_registry
    key:
      - java-rmi
#
  - service-names:
      - nfs
      - rpc-nfs_acl
    port: 2049
    key:
      - nfs
#
  - service-names:
      - nfs_acl
      - rpc-nfs_acl
    port: 2049
    key:
      - nfs_acl
#
  - service-names:
      - nfs
      - rpc-nfs
    port: 2049
    key:
      - nfs
#
  - service-names:
      - nfs
      - rpc
    port: 2463
    key:
      - nfs/rpc
#
  - service-names:
      - nlockmgr
      - rpc
    key:
      - rpc
