# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: astral-sh/ruff-action@v3
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format
        run: ruff format --diff .

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest] #macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run pytest
