name: Test on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        # not really needed, but upgrades python to latest 3.x
        # instead of using ubuntus older versions.
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
      - name: run
        run: |
          uv sync
          uv run scans2any
      - name: Run Tests
        run: |
          uv run pytest -v
